### PR TITLE
Make 'replace_calls_in_module' not dependent of kernel version nor

### PR DESCRIPTION
**Pull request by 8tab**
config.

This patch removes kernel version and CONFIG_DEBUG_SET_MODULE_RONX
ifdefs and adds runtime checks if module's code sections are RO and
should be set to RW before binary patching.

### CODE REVIEW

**Comment by 8tab** [comment]
I've uploaded v2 of this patch. Please use the latter for testing.

**Comment by euspectre** [comment]
Thanks, will take a look this week.

**Comment by euspectre** [comment]
The patch looks good to me except a couple of things

`is_module_section_rw()`:
The loop `while (tmp < (end + PAGE_SIZE)) {...}` may process one more page than needed.
Suppose _end == begin + 1000_, then the loop will check the addresses _begin_ and _begin+4096_ because both are less than _end+PAGE_SIZE==begin+5096_.

I'd suggest to just page-align down the starting address (well, it is probably aligned already but let us not count on that) and just use `tmp < end`. Something like this:

```c
	unsigned long tmp = begin & PAGE_MASK;
	pte_t* pte = NULL;
	unsigned int level = 0;

	// check if all pages spanning between 'begin' and 'end' are writeable
	while (tmp < end)
        ...
```
Another suggestion is to use `unsigned long` rather than `void*` in `is_module_section_rw()`, `is_module_{core|init}_text_rw()`. `lookup_address()` expects `unsigned long` and passing `void*` results in build error on some systems.

**Comment by 8tab** [comment]
Nice catch! I've modified the patch based on your review. and did a force push. Please check the latter.

**Comment by euspectre** [comment]
Thanks! It seems to work OK now.
Merged.

**Pull request merged**
